Feature/telerobot state configure
pashagray/telerobot pull request #1
Opened 2020-08-25 09:37 UTC by izhanov

2020-08-25 09:48 UTC, pashagray requested changes

2020-08-25 09:48 UTC, pashagray commented on lib/telerobot/state.rb
> +      end
думаю так не стоит делать. Метод new -- это плохая идея. Конфиг можно проверить в call. Более того нужно проверить, что именно токен отсутсвует, а не какой-нибудь другой параметр, которые 100% будут.

2020-08-25 09:48 UTC, pashagray commented on lib/telerobot/state.rb
> +            Add to your #{superclass} class configure class method
суперкласса может и не быть. Ничего не мешает сделать пользователю одностейтового бота с одним классом без базового. Поэтому нужно либо просто указать текущий класс.

2020-08-25 10:14 UTC, izhanov commented on lib/telerobot/state.rb
> +      end
Переместил проверку в ```#call```

2020-08-25 10:15 UTC, izhanov commented on lib/telerobot/state.rb
> +            Add to your #{superclass} class configure class method
Реализовал с указанием текущего класса

2020-08-26 03:22 UTC, pashagray approved these changes

2020-08-26 03:22 UTC, merged