[Feature]Added Telerobot::Telegram::Api for sending messages
pashagray/telerobot pull request #3
Opened 2020-08-26 09:28 UTC by izhanov

2020-08-27 04:06 UTC, pashagray requested changes

2020-08-27 04:06 UTC, pashagray commented on lib/telerobot/chat.rb
> +require_relative "./telegram/api"
Это нужно перенести telerobot.rb, где подключаются все файлы

2020-08-27 04:06 UTC, pashagray commented on lib/telerobot/state.rb
> +      end
Это же вроде уже слито?

2020-08-27 04:06 UTC, pashagray commented on lib/telerobot/telegram/api.rb
> +      end
Вот это нужно переделывать. Очень неявно получается. API как бы вырывается с кишками из Chat.rb используя все его переменные. Поэтому нужно API сделать отдельным классом, который принимает в только боди и путь куда отправить.

2020-08-30 06:13 UTC, izhanov commented
Rejected

2020-08-30 06:13 UTC, closed without merging